Answered question to when to use node
emmawedekind/Front-End-FAQ pull request #31
Opened 2018-11-20 18:30 UTC by daniel-vera-g

Answered the question to where and when to use nodejs.

2018-11-26 19:17 UTC, emmabostian requested changes
Just a minor capitalization nitpick! Let me know once it's fixed!

2018-11-26 19:17 UTC, emmawedekind commented on node.md
> +With Node you get a Robust technology stack, it is fast due to it's event based character, you can use it very good for scaling(Microservices) and it has a rich ecosystem. On the Other hand, due to h
```suggestion
With Node you get a Robust technology stack, it is fast due to it's event based character, you can use it very good for scaling(Microservices) and it has a rich ecosystem. On the other hand, due to his non-blocking I/O it is not suited for computation-heavy tasks like machine learning.
```

2018-11-26 19:29 UTC, daniel-vera-g commented
Used your suggestion. Should be updated.

2018-11-28 12:01 UTC, emmabostian approved these changes
Thanks!

2018-11-28 12:01 UTC, merged