Add a page "Staying up to date"
emmawedekind/Front-End-FAQ pull request #44
Opened 2018-12-11 20:02 UTC by aibolik

2018-12-12 06:28 UTC, emmabostian requested changes
This is so great thanks! Just a couple of minor comments. Additionally you should add Sarah Drasner!

2018-12-12 06:28 UTC, emmabostian commented on README.md
> +[Staying up to date](to-follow.md)
```suggestion
[Staying up to date](staying-up-to-date.md)
```

2018-12-12 06:28 UTC, emmabostian commented on to-follow.md
> +# Staying up to date
Please re-name this file to `staying-up-to-date.md`

2018-12-12 06:28 UTC, emmabostian commented on to-follow.md
> +> This is an opiniated list of influencers and other people/companies who are really good at what they are doing. They all relate somehow to FrontEnd and/or JavaScript and most of them constantly sha
```suggestion
> This is an opiniated list of influencers and other people/companies who are really good at what they are doing. They all relate somehow to FrontEnd and/or JavaScript and most of them constantly share knowledge through blog posts and/or Twitter discussions. Feel free to contribute to this list.
```

2018-12-12 06:28 UTC, emmabostian commented on to-follow.md
> +- Kyle Simpson([@getify](https://twitter.com/getify)) - when we talk about JavaScript it is unfair to not include Kyle Simpson, also knows as GETIFY. My foundation of JavaScript strengthened after re
```suggestion
- Kyle Simpson([@getify](https://twitter.com/getify)) - when we talk about JavaScript it is unfair to not include Kyle Simpson, also known as GETIFY. My foundation of JavaScript strengthened after reading his [You Don't Know JS](https://github.com/getify/You-Dont-Know-JS) book series. I highly recommend to all new JS devs (not only beginners) . You should go to his Twitter account, learn about him, and read the two books mentioned in his profile.
```

2018-12-13 13:21 UTC, aibolik commented
@emmawedekind sure, thanks for feedback. Will update

2018-12-14 20:10 UTC, aibolik commented
@emmawedekind  Can you please review? I've made changes you asked. Thanks

P.S.: I was just not sure if GitHub makes notifications that I made changes.

2018-12-18 08:02 UTC, emmabostian approved these changes
Great thanks!

2018-12-18 08:02 UTC, merged